"""empty message

Revision ID: 654e7829dbc8
Revises: c4daabc8f928
Create Date: 2023-05-05 16:18:29.674059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "654e7829dbc8"
down_revision = "c4daabc8f928"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint("collections_posts_id_fkey", type_="foreignkey")
        batch_op.create_foreign_key(None, "posts", ["post_id"], ["id"])
        batch_op.drop_column("posts_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("posts_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "collections_posts_id_fkey", "posts", ["posts_id"], ["id"]
        )
        batch_op.drop_column("post_id")

    # ### end Alembic commands ###
